apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: elastic-system
spec:
  ca:
    secretName: tls-otokoc
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-es-cert
  namespace: elastic-system
spec:
  isCA: true
  dnsNames:
    - elasticsearch-es-http
    - elasticsearch-es-http.elastic-system.svc
    - elasticsearch-es-http.elastic-system.svc.cluster.local
    - elasticsearch-kb-http
    - elasticsearch-kb-http.elastic-system.svc
    - elasticsearch-kb-http.elastic-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: tls-otokoc
  subject:
    organizations:
      - elasticsearch
      - kibana