apiVersion: maps.k8s.elastic.co/v1alpha1
kind: ElasticMapsServer
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 7.17.3
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic-system