apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: paircore-sts-deployment
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paircore-sts-deployment
  targetCPUUtilizationPercentage: 70
status:
  currentReplicas: 0
  desiredReplicas: 0
