apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
spec:
  storageClassName: ""
  resources:
    requests:
       storage: 50Gi
  volumeMode: Filesystem
  volumeName: pv-redis
  accessModes:
    - ReadWriteOnce